Hubapi documentation
jina-ai/cloud-ops pull request #73
Opened 2021-01-19 11:00 UTC by rutujasurve94

Documentation for:
- `hub list`
- `hub push`

2021-01-19 11:12 UTC, cristianmtr commented on hubapi/README.MD
> +`HubAPI`
```suggestion
# HubAPI

```

2021-01-19 11:12 UTC, cristianmtr commented on hubapi/README.MD
> +1. `Hub List` API
```suggestion

## Hub List API

```

2021-01-19 11:13 UTC, cristianmtr commented on hubapi/README.MD
> +2. `Hub Push` API
```suggestion

## Hub Push API

```

2021-01-19 11:13 UTC, cristianmtr commented on hubapi/README.MD
> +The HubAPI supports operations for listing jina hub images
Why are there line feeds within the paragraph?

2021-01-19 11:15 UTC, cristianmtr commented on hubapi/README.MD
> +* API gateway endpoint: `/GET` `images`
Shouldn't it be `GET /images`?

2021-01-19 11:16 UTC, cristianmtr commented on hubapi/README.MD
> +List API provides the user the ability to query jina images. Under the hood, the implementation uses a Mongodb Handler to connect to the database & insert documents in the collection.
```suggestion
List API provides the user the ability to query `Jina` images. Under the hood, the implementation uses a `MongodbHandler` to connect to the database & insert documents in the collection.
```

Make sure wrap any code-related words in ``

2021-01-19 11:17 UTC, cristianmtr commented on hubapi/README.MD
> +    Stage 1:
This is rendered as code. Unindent it

2021-01-19 11:18 UTC, cristianmtr requested changes
some style changes

2021-01-19 11:18 UTC, alexcg1 requested changes
Nice work overall - just a few polishing/formatting tweaks :smile:

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +The HubAPI supports operations for listing jina hub images
When we're talking about Jina Hub outside of the actual command line, call it **J**ina **H**ub

On command line or code blocks use `jina hub`

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +hub authorizer. We use MongoDB for storing and retrieving
Capitalize **H**ub in all cases when used in text (not code)

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +1. `Hub List` API
`hub list` since its a command (all commands should be exactly as you'd write on command line)

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +List API provides the user the ability to query jina images. Under the hood, the implementation uses a Mongodb Handler to connect to the database & insert documents in the collection.
*List API provides the user the ability to query jina images*

Simplify to:

*The list API lets users query **Jina** images*

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +Documents are generally manifest files that have metadata information of hub images. Currently, the List API is optimised for listing the images with the latest jina version.
jina -> Jina

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +
For this section, can we break stages down into their own sub-headings?

`Stage 1:` -> `### Stage 1`

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +    }
Should this be in a code block?

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +     - 1st element of the `images` list would be the latest executor
1st -> First

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +    - Fetch n results at a time
*n* - if it's just a number placeholder
`n` - if we're referring to an actual variable

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +`HubAPI`
Make this a top-level heading?

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +Documents are generally manifest files that have metadata information of hub images. Currently, the List API is optimised for listing the images with the latest jina version.
Are they *generally* manifest files, or *always*? (I don't actually know. If always, can remove `generally` here)

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +`executor name` (simple regex search).
Maybe better as a table

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +    - Sort by `name`, `jina_version` & `version`
`&` -> `and` (more formal, better for docs)

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +    - `name`: 1 - this sorts alphabetically (set to -1 for reverse order)
Wrap things like `1` and `-1` in backticks since they're variables

2021-01-19 11:18 UTC, alexcg1 commented on hubapi/README.MD
> +    - Finalize the set of arguments to be set
Finalize the arguments to be set

2021-01-19 12:53 UTC, deepankarm commented
I think the task is misunderstood. Since we are talking about an `API` endpoint, we can have auto-generated `openapi` docs which can be used to deploy to one of our github pages - e.g.- https://api.jina.ai/daemon/

We need to follow [Documenting REST APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api.html) section to add these docs as an openapi json directly in API Gateway. And this json needs to be part of `cloud-ops` CD to be deployed as a Github page (this can be done later). Through this, we wouldn't need to maintain a separate markdown file.

2021-01-19 14:22 UTC, rutujasurve94 commented
Sure, I am moving the content to `openapi` docs on `APIGateway` console. We can merge this PR later if required.

2021-01-25 13:37 UTC, cristianmtr commented
So should we close this PR for now?

2021-01-27 06:31 UTC, nan-wang commented
close the PR for the time being.

2021-01-27 06:31 UTC, closed without merging