fix: allow passing of flow id
jina-ai/cloud-ops pull request #85
Opened 2021-01-29 13:01 UTC by cristianmtr

2021-01-29 13:01 UTC, cristianmtr commented
Testing on docker now

2021-01-29 13:51 UTC, JoanFM reviewed
Good looking, next iteration would be switching between indexer tyoes

2021-01-29 17:20 UTC, JoanFM requested changes

2021-01-29 17:20 UTC, JoanFM commented on stress-example/image/index.yml
> -    needs: [gateway]
do not remove this, this will need to be kept this way, working on enabling it

2021-01-29 17:20 UTC, JoanFM commented on stress-example/text/index.yml
> -    needs: gateway
do not remove this, this is important for the test, the most u can do is comment it out

2021-02-01 09:27 UTC, JoanFM approved these changes

2021-02-01 09:28 UTC, merged